name: Build and deploy a container to an Azure Web App
on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment (using Node.js 20 compatible version)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/hiro-api:${{ github.sha }} .
      - name: Azure login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
            allow-no-subscriptions: false
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
            azcliversion: latest
            inlineScript: |
              az account show
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/hiro-api:${{ github.sha }}